os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.2
  - 1.3
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia:
        - 1.3
        - nightly
  include:
    - stage: deploy docs
      os: linux
      julia: 1.2
      script:
        - julia -e 'import Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
      after_success: skip

notifications:
  email: false

after_success:
  - julia -e 'import Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
